### ISSUE TITLE
Query - Location of Tyna's screencast on adding new data sources

### ISSUE THREAD

**Issue by peanutbutter-memory** [gtif-cerulean/catalog#10]
In terms of adding new data, found https://github.com/gtif-cerulean/catalog/wiki/Data-integration-steps.

I recall from a previous meeting that Tyna recorded and mentioned re-recording video on steps to add a new data source.

Is this available somewhere @santilland?

**Comment by santilland** [comment]
@peanutbutter-memory i am not able to find the recording, will try to further inquiry about it. In any case, if there are any questions on what is in the data integration steps i would be happy to help.

**Comment by peanutbutter-memory** [comment]
Thanks Daniel 😊

Cheers,

Richard

Richard Burcher (he/him, il/lui)

Software Specialist
Ocean, Coastal and River Engineering National Research Council
National Research Council Canada / Government of Canada
1200, chemin Montreal Road, M-32, Ottawa, ON  K1A 0R6

Office 223
+1 343-990-8587
***@***.******@***.***>


Developpeur Logiciels
Génie Océanique, Côtier et Fluvial
Conseil national de recherches Canada / Gouvernement du Canada
1200, chemin Montreal Road, M-32, Ottawa, ON  K1A 0R6

Office 223
+1 343-990-8587
***@***.******@***.***>

**Comment by santilland** [comment]
@peanutbutter-memory it seems at the end there was no recording, that is why i could not find it 😊
I hope the documentation is still understandable, i think it goes over all important points well. As i said i would be happy to help with any concrete questions of things that might not be clear, i will close this issue for now.
For further questions feel free to open new issues.
